input_schedule/urls.py
from django.conf.urls import url
from .views import *

urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^result', displayResults, name='sched_result'),
]

main_models/urls.py
from django.conf.urls import url
from .views import *

presistant/urls.py
from django.conf.urls import url, include
from django.contrib import admin
import input_schedule.urls as core

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^',include(core,namespace='core'))
]

input_schedule/models.py
from django.db import models

main_models/models.py
from django.db import models


# Create your models here.
class Event(models.Model):
    id = models.IntegerField(editable=False, primary_key=True)
    name = models.TextField(max_length=30)
    place = models.TextField(max_length=30)
    day = models.TextField(max_length=9)
    startTime = models.IntegerField(editable=False)


class Schedule(models.Model):
    OWNER_CHOICES = [
        ('P', 'President'),
        ('VP', 'Vice President')
    ]

    id = models.IntegerField(editable=False, primary_key=True)
    owner = models.TextField(max_length=2, choices=OWNER_CHOICES)

input_schedule/forms.py
from django import forms

input_schedule/views.py
from django.shortcuts import render
from django.views.decorators.csrf import csrf_exempt
from .algorithms import *

response = {}

# Create your views here.
def index(request):
    html = "input_schedule.html"
    return render(request, html)

@csrf_exempt
def displayResults(request):
    eventCount = request.POST['count']
    events = []

    for x in range(int(eventCount)):
        id = x + 1
        name = request.POST['name' + str(id)]
        place = request.POST['loc' + str(id)]
        day = request.POST['day' + str(id)]

        timeStr = request.POST['time' + str(id)]
        time = int(timeStr)

        event = Event(id, name, place, day, time)
        events.append(event)

    schedules = [Schedule(1, 'P'), Schedule(2, 'VP')]

    pop = initializePopulation(events, schedules)
    res = geneticAlgorithm(pop, schedules)

    response['president'] = set(res.individual.get(schedules[0]))
    response['vice_president'] = set(res.individual.get(schedules[1]))

    html = "schedule_result.html"

    return render(request, html, response)

input_schedule/templates/input_schedule.html
<!DOCTYPE html>
{% extends "base.html" %}
{% load staticfiles %}
{% load static %}
{% block content %}
    <div class="py-5 bg-aquamarine">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <h1 class="mt-4 mb-4 text-center display-4 text-light text-weight-bold"><b>Tambahkan Acara</b></h1>
                </div>
            </div>
            <div class="col-lg-6 mx-auto row p-4 bg-light animate-in-down event-form-box" style="">
                <div class="col-md-12">
                    <div class="row">
                        <div class="col-md-12">
                            <form class="input-append" method="POST" action="{% url 'core:sched_result' %}">
                                {%  csrf_token %}
                                <input type="hidden" name="count" id="count" value="1">

                                <div id="field">

                                    <div class="form-group" id="name1" ><label>Nama Acara</label> <input type="text" name="name1"
                                                                                                         class="form-control"
                                                                                                         placeholder="Masukkan nama acara">
                                    </div>
                                    <div class="form-group" id="loc1"><label>Lokasi Acara</label> <input type="text" name="loc1"
                                                                                                           class="form-control"
                                                                                                           placeholder="Masukkan lokasi acara">
                                    </div>
                                    <div class="form-group" id="day1"><label>Hari Acara</label><select name="day1" class="form-control">
                                        <option value="Senin">Senin</option>
                                        <option value="Selasa">Selasa</option>
                                        <option value="Rabu">Rabu</option>
                                        <option value="Kamis">Kamis</option>
                                        <option value="Jumat">Jumat</option>
                                    </select></div>
                                    <div class="form-group" id="time1"><label>Waktu Acara</label>
                                        <select
                                            name="time1" class="form-control">
                                            <option value="10">10.00 - 11.00</option>
                                            <option value="11">11.00 - 12.00</option>
                                            <option value="12">12.00 - 13.00</option>
                                            <option value="13">13.00 - 14.00</option>
                                            <option value="14">14.00 - 15.00</option>
                                            <option value="15">15.00 - 16.00</option>
                                            <option value="16">16.00 - 17.00</option>
                                        </select></div>



                                    <button type="button" class="btn mt-4 btn-block p-2 btn-outline-secondary add-more">
                                        <b>Tambah
                                            Acara</b></button>

                                    <hr class="mt-4 mb-4">

                                    <button type="submit" class="btn mt-4 btn-block p-2 btn-primary"><b>Submit Acara</b>
                                    </button>

                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

input_schedule/templates/schedule_result.html
<!DOCTYPE html>
{% extends "base.html" %}
{% load staticfiles %}
{% load static %}
{% block content %}
    <div class="py-5 bg-aquamarine">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <h1 class="mt-4 mb-4 text-center display-4 text-light text-weight-bold"><b>Presiden</b></h1>
                </div>
            </div>
            <div class="col-lg-12 mx-auto row p-4 bg-light animate-in-down event-form-box" style="">
                <div class="table-responsive">
                    <table class="table table-bordered ">
                        <thead class="thead-dark">

                        <tr>
                            <th>Hari</th>
                            <th>Jam</th>
                            <th>Nama Acara</th>
                        </tr>

                        </thead>
                        <tbody>
                        {% for x in president %}
                            <tr>
                                <td>{{ x.day }}</td>
                                <td>{{ x.startTime }}</td>
                                <td>{{ x.name }}</td>
                            </tr>
                            <tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <h1 class="mt-4 mb-4 text-center display-4 text-light text-weight-bold"><b>Wakil Presiden</b></h1>
                </div>
            </div>
            <div class="col-lg-12 mx-auto row p-4 bg-light animate-in-down event-form-box" style="">
                <div class="table-responsive">
                    <table class="table table-bordered ">
                        <thead class="thead-dark">
                        <tr>
                            <th>Hari</th>
                            <th>Jam</th>
                            <th>Nama Acara</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for x in vice_president %}
                            <tr>
                                <td>{{ x.day }}</td>
                                <td>{{ x.startTime }}</td>
                                <td>{{ x.name }}</td>
                            </tr>
                            <tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/base.html
{% load staticfiles %}
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- PAGE settings -->
    <link rel="icon" href="https://templates.pingendo.com/assets/Pingendo_favicon.ico">
    <title>Masukkan Acara - PreSistant</title>
    <meta name="description" content="Free Bootstrap 4 Pingendo Aquamarine template for restaurant and food">
    <meta name="keywords" content="Pingendo restaurant food aquamarine free template bootstrap 4">
    <!-- CSS dependencies -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"
          type="text/css">
    <link rel="stylesheet" href="{% static 'css/aquamarine.css' %}" type="text/css">
    <!-- Script: Make my navbar transparent when the document is scrolled to top -->
    <script src="{% static 'js/navbar-ontop.js' %}"></script>
    <!-- Script: Animated entrance -->
    <script src="{% static 'js/animate-in.js' %}"></script>

</head>

<body>
<header>
    {% include "partials/header.html" %}
</header>
<content>
    {% block content %}
        <!-- content goes here -->
    {% endblock %}
</content>
</body>
<footer>
    {% block footer %}
        {% include "partials/footer.html" %}
    {% endblock %}
</footer>
<!-- JavaScript dependencies -->
<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
        integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" crossorigin="anonymous" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"></script>
<script src = "{% static 'js/smooth-scroll.js' %}" ></script>
<script src="{% static 'js/dynamic_form.js' %}"></script>
</html>

templates/partials/footer.html
<div class="bg-dark pt-4">
    <div class="container">
        <div class="row">
            <div class="col-md-12 p-2">
                <h2 class="mb-4 text-weight-bold">SC4</h2>
                <p class="m-0">
                    <a href="https://gitlab.com/alputri/presistant-2.0" class="text-white">Gitlab</a>
                </p>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12 mt-3">
                <p class="text-center text-muted">© Copyright 2018 SC4 - All rights reserved. </p>
            </div>
        </div>
    </div>
</div>

templates/partials/header.html
<nav class="navbar navbar-expand-md navbar-light fixed-top bg-primary">
    <div class="container"><a class="navbar-brand text-light" href="{% url 'core:index' %}">
        <i class="fa d-inline fa-lg fa-circle-o"></i>
        <b> PreSistant</b>
    </a>
        <button class="navbar-toggler navbar-toggler-right border-0" type="button" data-toggle="collapse"
                data-target="#navbar5">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbar5">
            <ul class="navbar-nav mr-auto">
            </ul>
            <ul class="navbar-nav ml-auto">
            </ul>
            <a class="btn btn-secondary navbar-btn ml-md-2" href="{% url 'core:index' %}">Tambah Acara</a>
        </div>
    </div>
</nav>